// Test generated by RoostGPT for test demo56 using AI Type Open AI and AI Model gpt-4

package main

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
)

type BasicResponse struct {
	Status  int    `json:"status"`
	Message string `json:"message"`
}

func handleInvalidMethod(w http.ResponseWriter, r *http.Request) {
	resp := &BasicResponse{
		Status:  http.StatusMethodNotAllowed,
		Message: "No such endpoint",
	}
	writeBasicResponse(w, resp)
}

func writeBasicResponse(w http.ResponseWriter, resp *BasicResponse) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

func TestHandleInvalidMethod_58fd8542d1(t *testing.T) {
	req, err := http.NewRequest("GET", "", nil)
	if err != nil {
		t.Fatal(err)
	}

	rr := httptest.NewRecorder()
	handler := http.HandlerFunc(handleInvalidMethod)

	handler.ServeHTTP(rr, req)

	if status := rr.Code; status != http.StatusMethodNotAllowed {
		t.Errorf("handler returned wrong status code: got %v want %v", status, http.StatusMethodNotAllowed)
	}

	expected := `{"status":405,"message":"No such endpoint"}`
	if rr.Body.String() != expected {
		t.Errorf("handler returned unexpected body: got %v want %v", rr.Body.String(), expected)
	}
}
